model:
  base_learning_rate: 1.0e-05
  scale_lr: False
  target: lvdm.models.cogvideo_dpo.CogVideoXVideoDPO
  params:
    model_path: THUDM/CogVideoX-2b
    beta_dpo: 5000.0
    first_stage_key: video
    cond_stage_key: caption
    video_length: 49
    image_size:
    - 480
    - 720
    log_every_t: 20
    uncond_prob: 0.0
    torch_dtype: bf16
    gradient_checkpointing: True
    enable_slicing: True
    enable_tiling: True
    optimizer_beta1: 0.9
    optimizer_beta2: 0.95
    optimizer_epsilon: 1.0e-08
    weight_decay: 1.0e-04
    max_grad_norm: 1.0
    lora_args:
      adapter_name: cogvideox-dpo
      lora_rank: 64
      lora_alpha: 64
      lora_dropout: 0.0
      lora_scale: 1.0
      target_modules:
      - to_q
      - to_k
      - to_v
      - to_out.0

data:
  target: data.lightning_data.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 8
    wrap: false
    train:
      target: data.cogvideo_video_data.TextVideoDPO
      params:
        dupbeta: 0
        data_root: configs/cogvideo_dpo/vidpro/train_data.yaml
        resolution:
        - 480
        - 720
        video_length: 49
        subset_split: all

lightning:
  callbacks:
    batch_logger:
      params:
        batch_frequency: -1
    model_checkpoint:
      params:
        save_last: True
        filename: "{epoch:04}-{step:06}"
  trainer:
    accelerator: gpu
    benchmark: True
    log_every_n_steps: 1
    num_nodes: 1
    accumulate_grad_batches: 1
    max_epochs: 10
    precision: bf16
